#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}-{branch}

skip_tags: true

# branches to build
branches:
  only:
    - /jm_.*/

# skip commits with a commit message matching this regex
# note that [skip ci] and [skip appveyor] should work anyway
#skip_commits:
#  message: /\[chore\]/


#---------------------------------#
#    environment configuration    #
#---------------------------------#
image:
- Visual Studio 2015
- Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf true

# Limit the number of revisions in the history
clone_depth: 1

nuget:  
  disable_publish_on_pr: true

environment:
  COVERALLS_REPO_TOKEN:
    secure: x5HXnLkYkCzK7mWUW6O8QjNAaYNySKhI2Q20oah9i5mvnTk4U8jLJZnVb9MSxx0a

# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch
  - echo This is batch

matrix:
  fast_finish: true


#---------------------------------#
#       build configuration       #
#---------------------------------#

configuration: Release

build:
  parallel: true

  # MSBuild verbosity level
  verbosity: detailed

before_build:
  - nuget restore


#---------------------------------#
#       tests configuration       #
#---------------------------------#

# Install tools needed for Code Coverage, run instrumented tests, and report coverage numbers
after_test:
  - nuget install OpenCover -Version 4.6.519 -OutputDirectory tools
  - nuget install coveralls.net -Version 0.8.0-unstable0013 -PreRelease -OutputDirectory tools
  - .\tools\OpenCover.4.6.519\tools\OpenCover.Console.exe -target:nunit3-console.exe -targetargs:"--noheader .\Keen.NET.Test\bin\Release\Keen.Net.Test.dll .\Keen.NET_35.Test\bin\Release\Keen.NET_35.Test.dll" -filter:"+[*]* -[*.Test]*" -register:user
  - .\tools\coveralls.net.0.8.0-unstable0013\tools\csmacnz.Coveralls.exe --opencover -i .\results.xml