#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}-{branch}

skip_tags: true

# branches to build
branches:
  only:
    - /jm_.*/

# skip commits with a commit message matching this regex
# note that [skip ci] and [skip appveyor] should work anyway
#skip_commits:
#  message: /\[chore\]/


#---------------------------------#
#    environment configuration    #
#---------------------------------#
image:
- Visual Studio 2015
- Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf true

# Limit the number of revisions in the history
clone_depth: 1

nuget:  
  disable_publish_on_pr: true

environment:
  COVERALLS_REPO_TOKEN:
    secure: <blah>

# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch
  - echo This is batch

matrix:
  fast_finish: true


#---------------------------------#
#       build configuration       #
#---------------------------------#

configuration: Release

before_build:
  - nuget restore